version: '3'
services:
  qb:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    ports:
      - "4861:4861"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
    command: ["bash", "run.sh"]
  interactive:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    runtime: nvidia
    ports:
      - "4861:4861"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t