name: base
dependencies:
  - pytorch=0.4.1
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - nltk
  - requests=2.24.0
  - click
  - flask
  - pip:
    - wikipedia
channels:
  - anaconda
  - pytorch
