retriever: TFIDF
retriever_path: tfidf.pickle
retriever_conf:
  k: 10
retriever_train_args:

reranker: HAR
reranker_path: har_reranker.mdl
reranker_conf:
  weight: 0.015
  input_size: 768
  attention_dim: 512
  attention_heads: 16
  num_blocks: 3
reranker_train_args:
  wiki_dump: data/wiki_lookup.json
  dict_path: dict_dump.pickle
  batch_size: 128
  n_epoch: 20
